<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_session_login.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.ApiSessionLoginResponse</code>
 */
class ApiSessionLoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * return to site 
     *
     * Generated from protobuf field <code>string preSessionId = 1;</code>
     */
    private $preSessionId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $preSessionId
     *           return to site 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Platform\ApiSessionLogin::initOnce();
        parent::__construct($data);
    }

    /**
     * return to site 
     *
     * Generated from protobuf field <code>string preSessionId = 1;</code>
     * @return string
     */
    public function getPreSessionId()
    {
        return $this->preSessionId;
    }

    /**
     * return to site 
     *
     * Generated from protobuf field <code>string preSessionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPreSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->preSessionId = $var;

        return $this;
    }

}

